// Auto-generated by Setup-SwaAuth.ps1 — do not commit (gitignored)
window.AZ_STAMPER_CONFIG = {
  clientId: '4924e090-7b39-4957-9557-aae4e3e89a83',
  tenantId: 'dbb4b808-f0e6-469f-92d6-9788aef52734',
  configBlobUrl: 'https://azstampersta.blob.core.windows.net/config/stamper.json',
  appInsightsId: '/subscriptions/2f2d900c-03a4-4763-8138-bed4d299a7fa/resourceGroups/rg-az-stamper/providers/microsoft.insights/components/ai-az-stamper'
};
